### PR TITLE
fix: add missing cacheable metadata from URL

### PR DESCRIPTION
**Pull request by e0ipso**
It was gathered but I think it was not added to the render array.

### CODE REVIEW

**Comment by gabesullice** [comment]
@e0ipso are you actually seeing an error because of this?

I assumed that it was being captured by a `RenderContext` further up the stack. We can't rely on that in JSON:API, but can't we rely on it for this?

**Comment by gabesullice** [comment]
PS. @zrpnr and I were only using Github for more rapid initial development. We've since puth this project up on d.o: https://www.drupal.org/project/fluid_comment

**Comment by e0ipso** [comment]
> but can't we rely on it for this?
Hmm, you are probably right.




> We've since puth this project up on d.o: https://www.drupal.org/project/fluid_comment

good to know!

**Comment by gabesullice** [comment]
Closing for now.

**Pull request closed without merging**
