### PR TITLE
Do not add an additional `next` link on the last page.

### PR DESCRIPTION
**Pull request by gabesullice**

### CODE REVIEW

**Comment by zrpnr** [comment]
If I have 2 total pages, (page 0, page 1)
This fixes the "next" link on page 1, it no longer appears.

However on page 0 the last link still says 2.

**Comment by gabesullice** [comment]
> However on page 0 the last link still says 2.

🤦‍♂ 

good catch!

**Comment by zrpnr** [comment]
looks good now! last link is "1" on page 0 and "0" on page 1.

**Comment by zrpnr** [comment]
I mean prev is 0 on page 1... working correctly.

**Pull request merged**
